// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/gomicro/gomicro.proto

package microdemo_service_gomicro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Gomicro service

type GomicroService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Gomicro_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Gomicro_PingPongService, error)
}

type gomicroService struct {
	c    client.Client
	name string
}

func NewGomicroService(name string, c client.Client) GomicroService {
	return &gomicroService{
		c:    c,
		name: name,
	}
}

func (c *gomicroService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Gomicro.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gomicroService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Gomicro_StreamService, error) {
	req := c.c.NewRequest(c.name, "Gomicro.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gomicroServiceStream{stream}, nil
}

type Gomicro_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type gomicroServiceStream struct {
	stream client.Stream
}

func (x *gomicroServiceStream) Close() error {
	return x.stream.Close()
}

func (x *gomicroServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gomicroServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gomicroServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gomicroServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gomicroService) PingPong(ctx context.Context, opts ...client.CallOption) (Gomicro_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Gomicro.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gomicroServicePingPong{stream}, nil
}

type Gomicro_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type gomicroServicePingPong struct {
	stream client.Stream
}

func (x *gomicroServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *gomicroServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *gomicroServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gomicroServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gomicroServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *gomicroServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gomicro service

type GomicroHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Gomicro_StreamStream) error
	PingPong(context.Context, Gomicro_PingPongStream) error
}

func RegisterGomicroHandler(s server.Server, hdlr GomicroHandler, opts ...server.HandlerOption) error {
	type gomicro interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Gomicro struct {
		gomicro
	}
	h := &gomicroHandler{hdlr}
	return s.Handle(s.NewHandler(&Gomicro{h}, opts...))
}

type gomicroHandler struct {
	GomicroHandler
}

func (h *gomicroHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GomicroHandler.Call(ctx, in, out)
}

func (h *gomicroHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GomicroHandler.Stream(ctx, m, &gomicroStreamStream{stream})
}

type Gomicro_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type gomicroStreamStream struct {
	stream server.Stream
}

func (x *gomicroStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gomicroStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gomicroStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gomicroStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gomicroStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *gomicroHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GomicroHandler.PingPong(ctx, &gomicroPingPongStream{stream})
}

type Gomicro_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type gomicroPingPongStream struct {
	stream server.Stream
}

func (x *gomicroPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *gomicroPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gomicroPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gomicroPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gomicroPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *gomicroPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
